xconverters = {"age" : lambda x: float(x) / 100. }
            
xusecols = (
    "age",
    #"geoRegion",
    #"state",
    "htn",
    "chf",
    "copd",
    "MI",
    "diab_u",
    "diab_c",
    "obesity",
    "drug",
    #"healthPlan",
    #"alcohol",
    #"depres6",
    #"depres2",
    #"multi_fusion",
    #"drg",
    #"year",
    #"tbco",
    #"instr",
    #"anx2",
    #"anx6",
    #"schiz2",
    #"schiz6",
    #"bpd2",
    #"bpd6",
    "ageGrp",
    "multi_lami",
    "single_lami",
    #"planType",
    #"tbco_tx",
    "sex",
    "anyDrugs",
    #"pvd",
    #"charlson",
    #"indication",
    # "employment",
    "msa",
    #"pt_zip",
                
    #"DX1",
    #"DX2",
    #"DX3",
    #"DX4",
    #"DX5",
    #"DX6",
    #"DX7",
    #"DX8",
    #"DX9",
    #"DX10",
    #"DX11",
    #"DX12",
    #"DX13",
    #"DX14",
    #"DX15",
                
    #"PROC1",
    #"PROC2",
    #"PROC3",
    #"PROC4",
    #"PROC5",
    #"PROC6",
    #"PROC7",
    #"PROC8",
    #"PROC9",
    #"PROC10",
    #"PROC11",
    #"PROC12",
    #"PROC13",
    #"PROC14",
    #"PROC15",

    #"preopDays",
    #"totalPreopSupply",
    #"preopAntipsych",
    #"preopAntidep",
    #"preopBenzos",
    #"str_zip",
    "longitude",
    "latitude"
)
            


yconverters = {"num" : lambda x: float(x) / 100. }
            
yusecols = (
    #"num",
    #"subj",
    #"totalPostopSupply",
    #"totalPostopDays",
    "noOpiates",
    #"comp",
    #"cost_1yr",
    #"cost_2yr",
    #"readmit",
    #"length_stay",
    #"inpt_cost",
    #"cost_90d",
    #"dis_home"
)
